#pragma config(Sensor, dgtl1,  encode,         sensorQuadEncoder)
#pragma config(Motor,  port1,           rightBack,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightFront,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftBack,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftFront,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// 1127.90068 ticks for encoder
#define PI 3.14159265
task main()
{
	void calcTicks (float distInch, float diameter)
	{
		float calcNumTicks = 360/(diameter*PI)* distInch;
	}
	while(true){

	}


}
